services:
  frontend:
    image: rotaba/frontend:latest
    container_name: rotaba-frontend
    restart: unless-stopped
    build:
      context: /
      dockerfile: Dockerfile
    ports:
      - 4000:3000